# Generated by Django 4.0.6 on 2022-07-27 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_date', models.DateField()),
                ('solve_date', models.DateField()),
                ('elapsed_seconds', models.IntegerField()),
                ('checked', models.BooleanField()),
                ('revealed', models.BooleanField()),
                ('streak', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-solve_date'],
            },
        ),
    ]
