# Generated by Django 4.0.6 on 2022-08-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='checked',
            new_name='used_help',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='revealed',
        ),
    ]
